//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        public film()
        {
            this.juges = new HashSet<juge>();
        }
        public int code_film { get; set; }
        public string titre { get; set; }
        public string description_ { get; set; }
        public string langue { get; set; }
        public Nullable<System.DateTime> année_prod { get; set; }
        public Nullable<int> code_cat { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<juge> juges { get; set; }
    }
}
