//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class juge
    {
        public juge()
        {
            this.films = new HashSet<film>();
        }
    
        public int code_j { get; set; }
        public string nom { get; set; }
        public string prénom { get; set; }
        public string nationnalite { get; set; }
    
        public virtual ICollection<film> films { get; set; }
    }
}
